# See https://wiki.hypr.land/Configuring/Monitors/
# monitor name, resolution@refresh-rate, position, scale
monitor=DP-3, 2560x1440@239.97, 0x0, 1

exec-once = steam -silent
exec-once = java --module-path="/home/jonas/openjfx/javafx-sdk-24.0.2/lib" \
                   --add-modules=javafx.controls,javafx.fxml \
                   --add-exports javafx.controls/com.sun.javafx.scene.control.skin.resources=ALL-UNNAMED \
                   --add-exports javafx.base/com.sun.javafx.event=ALL-UNNAMED \
                   --enable-native-access=javafx.graphics \
                   -Dprism.verbose=true \
                   -jar /home/jonas/PcPanel/pcpanel-1.7-SNAPSHOT.jar quiet
